### ISSUE TITLE
Missing search results

### ISSUE THREAD

**Issue by KonradStanski** [sourcebot-dev/sourcebot#111]
The search:
`repo:^github\.com/torvalds/uemacs$ define`
https://www.sourcebot.dev/search/search?query=repo%3A%5Egithub%5C.com%2Ftorvalds%2Fuemacs%24%20define
shows a bunch of results in uemacs for define, but 
`repo:^github\.com/torvalds.* define`
https://www.sourcebot.dev/search/search?query=repo%3A%5Egithub%5C.com%2Ftorvalds.*%20define
does not include "define" results from uemacs.
The repo must be matching though, because:
`repo:^github\.com/torvalds.* ncol`
https://www.sourcebot.dev/search/search?query=repo%3A%5Egithub%5C.com%2Ftorvalds.*%20ncol
does contain uemacs results.

I think this is a bug? Would be good to dig deeper.

**Comment by brendan-kellam** [comment]
Looks like that search query returns so many results that the `maxMatchDisplayCount` limit (which defaults to 10000) is hit. If you click "(load more)", we multiply the display count by 2. For example, when the display count is 10000000, we get all of the results (including those that are in uemacs):
https://www.sourcebot.dev/search/search?query=repo%3A%5Egithub%5C.com%2Ftorvalds.*%20define&maxMatchDisplayCount=10000000

**Comment by KonradStanski** [comment]
Ah, whoops. Misunderstood the behaviour.
