### ISSUE TITLE
branch not indexed

### ISSUE THREAD

**Issue by elettrico** [sourcebot-dev/sourcebot#117]
I have this configuration:
```
{
    "$schema": "../schemas/v2/index.json",
    "repos": [
        {
            "type": "gitlab",
            "url": "https://gitlab.****.com",
            "token": "glpat-*****",
            "all": true,
            "revisions": [
                    "main",
                    "dev"
            ]
        }
    ]
}
```
But when I search, I can see only results from the main branch, also in the repositories page it shows only one branch per repository. Shouldn't it index the "dev" branch also?

**Comment by brendan-kellam** [comment]
It looks like your config is slightly off - `revisions` is of type object that has the property `branches`, which is where you want to specify your branches. E.g.,:
```
{
    "$schema": "../schemas/v2/index.json",
    "repos": [
        {
            "type": "gitlab",
            "url": "https://gitlab.****.com",
            "token": "glpat-*****",
            "all": true,
            "revisions": {
                "branches": [
                    "main",
                    "dev"
                ]
            }
        }
    ]
}
```

An enhancement we should make is to raise a warning / error when a configuration is incorrect.

Going to close this issue, feel free to re-open if this didn't fix your issue.
