### ISSUE TITLE
Searching with sourcebot is very slow, how can I optimize it?

### ISSUE THREAD

**Issue by j14ncn** [sourcebot-dev/sourcebot#122]
I have indexed 6,000 repos, and sourcebot is very slow when searching. How can I optimize it?
<img width="398" alt="image" src="https://github.com/user-attachments/assets/0cfc1df3-588b-4174-b439-fedcbd3827e9">

**Comment by brendan-kellam** [comment]
6,000 repositories is far beyond what we have benchmarked... 😅

What are the specs of the machine you're running Sourcebot on? Without further investigation, I'm guessing we are hitting a bottleneck on cpu performance, so maybe we could try throwing more compute at it and vertically scaling things?

**Comment by j14ncn** [comment]
```
vCPUs: 4
Memory: 8 GB
Baseline Performance: 3/burstable up to 12.5
Local Disk IOPS: 1,100,000
Network Bandwidth: Up to 500,000 Mbps
Network Packet Processing Capability: 4 packets per second (pps)
Number of Elastic Network Interfaces (ENIs): 4
Maximum number of IP addresses per ENI: 15
Maximum number of IP addresses across all ENIs: 15
Maximum number of ENIs: 16
Network Outbound Bandwidth: 40,000 Mbps/burstable up to 160,000 Mbps
Network Inbound Bandwidth: 2 Mbps/burstable up to 10 Mbps
```

**Comment by brendan-kellam** [comment]
Could you check how large your index directory is?

`docker exec sourcebot du -sh /data/.sourcebot/index`

**Comment by j14ncn** [comment]
```
[root@code-search-service sourcebot]# du -sh .sourcebot/*
4.0K	.sourcebot/config.json
6.4M	.sourcebot/db.json
33G	.sourcebot/index
167G	.sourcebot/repos

```

**Comment by j14ncn** [comment]
<img width="1517" alt="image" src="https://github.com/user-attachments/assets/1ee752bf-0656-4283-8c1e-6427ef94e576" />

**Comment by brendan-kellam** [comment]
Is this consistent for all searches or only for certain searches?

Nothing in your screenshot particularly jumped out to me... I will dig through the Zoekt codebase a bit and see what could be the bottleneck.

One hunch is memory is the limiting factor - would you be able to scale the amount of memory such that it is larger than the index size? So 33GB or more, and see performance then.

**Comment by j14ncn** [comment]
@brendan-kellam 
deploy sourcebot on k8s, without limiting cpu and memory, and now the search speed is very fast.

**Comment by brendan-kellam** [comment]
Sweet - going to close this issue. Feel free to reopen if needed
