### ISSUE TITLE
FR: Support indexing code hosted on a local Gitea instance

### ISSUE THREAD

**Issue by bereket42** [sourcebot-dev/sourcebot#13]
[Gitea](https://github.com/go-gitea/gitea) is a popular Git server in the self hosting community. I would love to be able to pair it with a self hosted sourcebot instance. Thanks!

**Comment by brendan-kellam** [comment]
Hey @bereket42 - thanks for filing a issue! Will take a closer look when I get the chance.

**Comment by adrenalinmike** [comment]
This would be highly appreciated, and it was the first feature I sought after installing Sourcebot.

**Comment by adam-blackwater** [comment]
I would be interested in seeing this work with the Gitea fork Forgejo

**Comment by brendan-kellam** [comment]
@adam-blackwater mind filing a separate issue for Forgejo?

**Comment by mvdkleijn** [comment]
Created #34 for Forgejo

**Comment by brendan-kellam** [comment]
We shipped Gitea support in [Release v2.1.0](https://github.com/sourcebot-dev/sourcebot/releases/tag/v2.1.0)!

**Comment by mvdkleijn** [comment]
> We shipped Gitea support in [Release v2.1.0](https://github.com/sourcebot-dev/sourcebot/releases/tag/v2.1.0)!

That should be theoretically easy to port to Forgejo since they're still compatible (though it **is** a hard fork)

**Comment by brendan-kellam** [comment]
@mvdkleijn yea good point - I will look into this later this week
