### ISSUE TITLE
Custom Gitlab URL not reflected in generated .netrc

### ISSUE THREAD

**Issue by tomusher** [sourcebot-dev/sourcebot#20]
When specifying a custom `GitLabURL` in the config, this URL is not reflected in the `.netrc` file generated by `entrypoint.sh`, so auth does not work without overriding the generated file.

**Comment by zapp42** [comment]
Perfect timing. You saved me some debugging. Thank you.
Confirmed.
Symptoms: The group hierarchy is created in the .sourcebot/repos folder, but no actual repository is cloned.

**Comment by brendan-kellam** [comment]
Hey thanks for raising. I will take a sec and get a custom GitLab instance going and will then take a look
