### ISSUE TITLE
Support self hosted GitHub (GitHub enterprise server) instances

### ISSUE THREAD

**Issue by cgill-21076** [sourcebot-dev/sourcebot#23]
https://docs.github.com/en/enterprise-server@3.14/admin/overview/about-github-enterprise-server

**Comment by brendan-kellam** [comment]
Heya - have you tried specifying the `GitHubUrl` [property in the config](https://github.com/sourcebot-dev/sourcebot/blob/main/schemas/index.json#L33)? 

Zoekt seems [to support GitHub enterprise](https://github.com/google/zoekt/issues/72), but I haven't actually gotten a chance to test this yet so I'd be curious to see if it works.

**Comment by cgill-21076** [comment]
I had not tried it. I missed that as an option when I was looking. I saw it for GitLab. Thank you for bringing it to my attention. It does seem to work with GitHub enterprise.

**Comment by brendan-kellam** [comment]
@cgill-21076 I'm trying to clarify a few things to help improve the docs, so had two questions (context: I don't have access to a GitHub enterprise server currently):

1. When setting the `GitHubUrl` property, was it set to something similar `https://github.mycompany.com`?
2. Did you happen to try to index a private repo in your deployment? I would assume the same issue with authentication and the `.netrc` file is happening here (see: #20)
