### ISSUE TITLE
Selfhosted instances of GitLab are not being assigned `gitlab` code host type

### ISSUE THREAD

**Issue by brendan-kellam** [sourcebot-dev/sourcebot#25]
When self-hosting a GitLab instance, we are not recognizing that the code host type is `gitlab`, resulting in some UI issues. E.g.:

Homepage carousel buttons do not link anywhere:
<img width="770" alt="image" src="https://github.com/user-attachments/assets/cd1155c0-ae1a-43b2-8970-67a577d99ded">

Codepreview header does not link anywhere:
<img width="190" alt="image" src="https://github.com/user-attachments/assets/591de6a0-0d8e-47ae-aef8-bcb2288ef44d">

Guessing this is the same story with a selfhosted GitHub instance, but will create a separate issue when validated.

**Comment by gaeljw** [comment]
I'm facing this as well (GitLab self hosted)
