### ISSUE TITLE
FR: Support indexing of branches

### ISSUE THREAD

**Issue by ultravigilante** [sourcebot-dev/sourcebot#29]
Sometimes I keep variants of my code on branches without intending to merge it into the default branch. Would be cool to see those in Sourcebot too.

**Comment by zapp42** [comment]
There is the "branch:xxxxx" search keyword, but I don't think it is working.

**Comment by brendan-kellam** [comment]
Yea there is the `branch` filter, but we only index `HEAD` atm so it's not too useful currently
