### ISSUE TITLE
/repos shows empty while indexing is ongoing

### ISSUE THREAD

**Issue by mdaniel** [sourcebot-dev/sourcebot#30]
It is probably a niche case, but is also a sub-optimal first user experience:

1. `vi config.json` to make reference to some big GH repo
2. docker run ...
3. Navigate to http://127.0.0.1:3000/ and see "indexing"
4. Navigate to http://127.0.0.1:3000/repos and see _nothing_
5. 🤔 wonder if something is going wrong

In my specific case, it took 6 minutes for zoekt to index the git repo sufficiently for it to show up and only then did that table populate with the repo and branches information

**Comment by brendan-kellam** [comment]
Hey @mdaniel - agreed this is currently suboptimal. Ideally, we would communicate progress per repository as they are indexed.

**Comment by kquinsland01** [comment]
> Ideally, we would communicate progress per repository as they are indexed.

Is there a way to do this with debug logging or similar? e.g. `docker run ... -e sourcebot_log_level=DEBUG ...`?

Currently have a `watch -n 5 ls data/repos... | wc -l` on a loop and once the number stops climbing I assume the initial spin up is "done".

**Comment by brendan-kellam** [comment]
Closing this since we added progress logs with the V2 release
