### ISSUE TITLE
Does this project support graphQL?

### ISSUE THREAD

**Issue by zhlmmc** [sourcebot-dev/sourcebot#89]
My case is to search programatically, not sure if sourcebot support API access through graphQL? Thanks!

**Comment by brendan-kellam** [comment]
Heya - we currently don't expose out an API surface, but it's something we have thought about. More likely than not, we would expose it as a REST endpoint to start - is graphQL a strict requirement for your use-case?

**Comment by zhlmmc** [comment]
> Heya - we currently don't expose out an API surface, but it's something we have thought about. More likely than not, we would expose it as a REST endpoint to start - is graphQL a strict requirement for your use-case?

REST is ok, thanks

**Comment by brendan-kellam** [comment]
Could you tell me more about your use case?

We do have a REST endpoint [hosted on the webserver](https://github.com/sourcebot-dev/sourcebot/blob/main/packages/web/src/app/api/(server)/search/route.ts) that is [used by the client](https://github.com/sourcebot-dev/sourcebot/blob/d9710c702defc19fb0591430edce5516e5699cda/packages/web/src/app/api/(client)/client.ts#L7), but we don't have official support for it yet (i.e., (1) it is not documented, and (2) we don't guarantee that the api surface will break across non-major revisions). This is something we have on our roadmap - created a issue to track: #101

To unblock for now, you can make a POST request to `/api/search` with a JSON body that conforms to [this schema](https://github.com/sourcebot-dev/sourcebot/blob/d9710c702defc19fb0591430edce5516e5699cda/packages/web/src/lib/schemas.ts#L3). The response is JSON conforming to [this schema](https://github.com/sourcebot-dev/sourcebot/blob/d9710c702defc19fb0591430edce5516e5699cda/packages/web/src/lib/schemas.ts#L83). Sample cURL request:

```sh
curl -X POST http://localhost:3000/api/search \
     -H "Content-Type: application/json" \
     -d '{"query": "hello", "maxMatchDisplayCount": 1000}'
```

This as as of [v2.5.4](https://github.com/sourcebot-dev/sourcebot/releases/tag/v2.5.4)

**Comment by brendan-kellam** [comment]
Closing this issue for now - feel free to re-open if needed

**Comment by kannae97** [comment]
> Heya - we currently don't expose out an API surface, but it's something we have thought about. More likely than not, we would expose it as a REST endpoint to start - is graphQL a strict requirement for your use-case?

Excuse me, is there a public REST api now?

**Comment by brendan-kellam** [comment]
@kannae97 Please see #101 - we don't have an "official" surface area as of now, but we have it coming up on our road map. #459 . You can still hit http://localhost:3000/api/search with the `X-Sourcebot-Api-Key` header set to a SB Api Key (same one MCP uses, see: https://docs.sourcebot.dev/docs/features/mcp-server#getting-started)
