### ISSUE TITLE
[GitLab] Archived repositories are indexed

### ISSUE THREAD

**Issue by gaeljw** [sourcebot-dev/sourcebot#91]
Given the following configuration for GitLab (self-hosted, but I don't think that should make a difference):
```json
{
    "type": "gitlab",
    "url": "https://gitlab.mycompany.net",
    "groups": [
        "my-group"
    ]
}
```

Then, the archived projects of the group `my-group` are indexed.

I would expect to not index archived projects by default. Maybe opt-in for indexation of archived projects with a config setting?

**Comment by gaeljw** [comment]
Maybe, partially related to https://github.com/sourcebot-dev/sourcebot/issues/39

**Comment by brendan-kellam** [comment]
Heya - you can use the `exclude.archived` option to exclude archived projects:
```jsonc
{
    "type": "gitlab",
    "url": "https://gitlab.mycompany.net",
    "groups": [
        "my-group"
    ],
    "exclude": {
        "archived": true
    }
}
```

Let me know if that solves things for you - happy to re-open if you are still hitting issues.

**Comment by gaeljw** [comment]
This works, thanks for the quick answer!
